# Credit Card Customer Churn Prediction Using ANN

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [7]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [8]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [9]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
df = pd.get_dummies(df, columns=['Geography','Gender'],drop_first=True)

In [12]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [13]:
X = df.drop(columns=['Exited'])
y = df['Exited']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,False,False,False

In [15]:
X_train.shape

(8000, 11)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
X_train_scaled

array([[ 0.35649971, -0.6557859 ,  0.34567966, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.20389777,  0.29493847, -0.3483691 , ...,  1.72572313,
        -0.57638802,  0.91324755],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.57946723,
         1.73494238,  0.91324755],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ..., -0.57946723,
        -0.57638802, -1.09499335],
       [ 0.15932282,  0.3900109 ,  1.03972843, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [ 0.47065475,  1.15059039, -1.38944225, ...,  1.72572313,
        -0.57638802,  0.91324755]], shape=(8000, 11))

In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()

model.add(Dense(300000, activation='relu', input_dim = 11))
model.add(Dense(30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

c:\Users\t5169\anaconda3\envs\Deep_Leearing\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 300000)         │     3,600,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │     9,000,030 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,600,061 (48.07 MB)

 Trainable params: 12,600,061 (48.07 MB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [24]:
history = model.fit(X_train_scaled, y_train, epochs=400000, validation_split=0.2)

Epoch 1/400000

200/200 ━━━━━━━━━━━━━━━━━━━━ 29s 143ms/step - accuracy: 0.8684 - loss: 0.3307 - val_accuracy: 0.8537 - val_loss: 0.3592
Epoch 2/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 136ms/step - accuracy: 0.8684 - loss: 0.3299 - val_accuracy: 0.8587 - val_loss: 0.3630
Epoch 3/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8687 - loss: 0.3242 - val_accuracy: 0.8562 - val_loss: 0.3559
Epoch 4/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8695 - loss: 0.3213 - val_accuracy: 0.8438 - val_loss: 0.3683
Epoch 5/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8695 - loss: 0.3206 - val_accuracy: 0.8525 - val_loss: 0.3614
Epoch 6/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8695 - loss: 0.3206 - val_accuracy: 0.8531 - val_loss: 0.3585
Epoch 7/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8722 - loss: 0.3153 - val_accuracy: 0.8519 - val_loss: 0.3581
Epoch 8/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8734 - loss: 0.3101 - val_accuracy: 0.8544 - val_loss: 0.3567
Epoch 9/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8767 - loss: 0.3095 - val_accuracy: 0.8575 - val_loss: 0.3731
Epoch 10/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8734 - loss: 0.3078 - val_accuracy: 0.8562 - val_loss: 0.3659
Epoch 11/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8763 - loss: 0.3050 - val_accuracy: 0.8594 - val_loss: 0.3663
Epoch 12/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 135ms/step - accuracy: 0.8766 - loss: 0.3018 - val_accuracy: 0.8481 - val_loss: 0.3685
Epoch 13/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8772 - loss: 0.3014 - val_accuracy: 0.8500 - val_loss: 0.3699
Epoch 14/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8783 - loss: 0.2950 - val_accuracy: 0.8475 - val_loss: 0.3854
Epoch 15/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8795 - loss: 0.2957 - val_accuracy: 0.8450 - val_loss: 0.3723
Epoch 16/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8839 - loss: 0.2884 - val_accuracy: 0.8556 - val_loss: 0.3683
Epoch 17/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8842 - loss: 0.2849 - val_accuracy: 0.8556 - val_loss: 0.3818
Epoch 18/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8814 - loss: 0.2834 - val_accuracy: 0.8506 - val_loss: 0.3767
Epoch 19/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 135ms/step - accuracy: 0.8852 - loss: 0.2790 - val_accuracy: 0.8487 - val_loss: 0.3837
Epoch 20/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.8850 - loss: 0.2797 - val_accuracy: 0.8469 - val_loss: 0.3884
Epoch 21/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 135ms/step - accuracy: 0.8861 - loss: 0.2752 - val_accuracy: 0.8338 - val_loss: 0.3927
Epoch 22/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8873 - loss: 0.2759 - val_accuracy: 0.8338 - val_loss: 0.3971
Epoch 23/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8927 - loss: 0.2665 - val_accuracy: 0.8581 - val_loss: 0.4245
Epoch 24/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8877 - loss: 0.2708 - val_accuracy: 0.8475 - val_loss: 0.4133
Epoch 25/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8958 - loss: 0.2605 - val_accuracy: 0.8525 - val_loss: 0.4227
Epoch 26/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.8923 - loss: 0.2557 - val_accuracy: 0.8350 - val_loss: 0.4348
Epoch 27/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.8958 - loss: 0.2541 - val_accuracy: 0.8444 - val_loss: 0.4179
Epoch 28/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.8905 - loss: 0.2565 - val_accuracy: 0.8462 - val_loss: 0.4107
Epoch 29/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.8963 - loss: 0.2494 - val_accuracy: 0.8363 - val_loss: 0.4360
Epoch 30/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.8991 - loss: 0.2461 - val_accuracy: 0.8400 - val_loss: 0.4391
Epoch 31/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9011 - loss: 0.2414 - val_accuracy: 0.8325 - val_loss: 0.4233
Epoch 32/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9000 - loss: 0.2423 - val_accuracy: 0.8375 - val_loss: 0.4548
Epoch 33/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.9003 - loss: 0.2434 - val_accuracy: 0.8381 - val_loss: 0.4511
Epoch 34/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9041 - loss: 0.2348 - val_accuracy: 0.8394 - val_loss: 0.4300
Epoch 35/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9080 - loss: 0.2313 - val_accuracy: 0.8475 - val_loss: 0.4316
Epoch 36/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9081 - loss: 0.2226 - val_accuracy: 0.8438 - val_loss: 0.4514
Epoch 37/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 132ms/step - accuracy: 0.9070 - loss: 0.2244 - val_accuracy: 0.8306 - val_loss: 0.4709
Epoch 38/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9095 - loss: 0.2197 - val_accuracy: 0.8394 - val_loss: 0.4703
Epoch 39/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9086 - loss: 0.2250 - val_accuracy: 0.8369 - val_loss: 0.4870
Epoch 40/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 132ms/step - accuracy: 0.9106 - loss: 0.2160 - val_accuracy: 0.8369 - val_loss: 0.4873
Epoch 41/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9162 - loss: 0.2051 - val_accuracy: 0.8400 - val_loss: 0.4828
Epoch 42/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9120 - loss: 0.2073 - val_accuracy: 0.8350 - val_loss: 0.5041
Epoch 43/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9112 - loss: 0.2084 - val_accuracy: 0.8238 - val_loss: 0.5057
Epoch 44/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9181 - loss: 0.1980 - val_accuracy: 0.8425 - val_loss: 0.5443
Epoch 45/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9197 - loss: 0.1969 - val_accuracy: 0.8419 - val_loss: 0.5492
Epoch 46/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9194 - loss: 0.1927 - val_accuracy: 0.8231 - val_loss: 0.5103
Epoch 47/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9184 - loss: 0.1933 - val_accuracy: 0.8313 - val_loss: 0.5695
Epoch 48/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9222 - loss: 0.1899 - val_accuracy: 0.8313 - val_loss: 0.5477
Epoch 49/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 132ms/step - accuracy: 0.9198 - loss: 0.1918 - val_accuracy: 0.8188 - val_loss: 0.5446
Epoch 50/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9258 - loss: 0.1836 - val_accuracy: 0.8375 - val_loss: 0.5044
Epoch 51/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9236 - loss: 0.1873 - val_accuracy: 0.8100 - val_loss: 0.5304
Epoch 52/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 136ms/step - accuracy: 0.9319 - loss: 0.1746 - val_accuracy: 0.8325 - val_loss: 0.5707
Epoch 53/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 134ms/step - accuracy: 0.9270 - loss: 0.1747 - val_accuracy: 0.8388 - val_loss: 0.5666
Epoch 54/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9356 - loss: 0.1698 - val_accuracy: 0.8331 - val_loss: 0.6373
Epoch 55/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9250 - loss: 0.1799 - val_accuracy: 0.8206 - val_loss: 0.5708
Epoch 56/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9300 - loss: 0.1719 - val_accuracy: 0.8200 - val_loss: 0.5692
Epoch 57/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 132ms/step - accuracy: 0.9298 - loss: 0.1710 - val_accuracy: 0.8200 - val_loss: 0.5780
Epoch 58/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9264 - loss: 0.1755 - val_accuracy: 0.8338 - val_loss: 0.6187
Epoch 59/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9373 - loss: 0.1628 - val_accuracy: 0.8313 - val_loss: 0.6328
Epoch 60/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9358 - loss: 0.1594 - val_accuracy: 0.8238 - val_loss: 0.6312
Epoch 61/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 132ms/step - accuracy: 0.9362 - loss: 0.1629 - val_accuracy: 0.8363 - val_loss: 0.6524
Epoch 62/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9414 - loss: 0.1449 - val_accuracy: 0.7969 - val_loss: 0.6360
Epoch 63/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9389 - loss: 0.1635 - val_accuracy: 0.8294 - val_loss: 0.6664
Epoch 64/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 132ms/step - accuracy: 0.9398 - loss: 0.1524 - val_accuracy: 0.8200 - val_loss: 0.6575
Epoch 65/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9459 - loss: 0.1428 - val_accuracy: 0.8056 - val_loss: 0.6534
Epoch 66/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9408 - loss: 0.1483 - val_accuracy: 0.8138 - val_loss: 0.6647
Epoch 67/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9377 - loss: 0.1571 - val_accuracy: 0.8094 - val_loss: 0.6696
Epoch 68/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 133ms/step - accuracy: 0.9436 - loss: 0.1471 - val_accuracy: 0.8288 - val_loss: 0.7000
Epoch 69/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 26s 132ms/step - accuracy: 0.9428 - loss: 0.1429 - val_accuracy: 0.8100 - val_loss: 0.6921
Epoch 70/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 27s 135ms/step - accuracy: 0.9420 - loss: 0.1422 - val_accuracy: 0.7844 - val_loss: 0.6638
Epoch 71/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9452 - loss: 0.1445 - val_accuracy: 0.8219 - val_loss: 0.7033
Epoch 72/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9431 - loss: 0.1426 - val_accuracy: 0.8363 - val_loss: 0.7689
Epoch 73/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9505 - loss: 0.1267 - val_accuracy: 0.8150 - val_loss: 0.6747
Epoch 74/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9509 - loss: 0.1296 - val_accuracy: 0.8056 - val_loss: 0.7256
Epoch 75/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9455 - loss: 0.1416 - val_accuracy: 0.8125 - val_loss: 0.7295
Epoch 76/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9447 - loss: 0.1447 - val_accuracy: 0.8100 - val_loss: 0.7475
Epoch 77/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 31s 153ms/step - accuracy: 0.9530 - loss: 0.1227 - val_accuracy: 0.8175 - val_loss: 0.7678
Epoch 78/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9469 - loss: 0.1342 - val_accuracy: 0.8281 - val_loss: 0.7240
Epoch 79/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9527 - loss: 0.1333 - val_accuracy: 0.8238 - val_loss: 0.7987
Epoch 80/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9531 - loss: 0.1223 - val_accuracy: 0.8238 - val_loss: 0.7289
Epoch 81/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9506 - loss: 0.1292 - val_accuracy: 0.8188 - val_loss: 0.7472
Epoch 82/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9514 - loss: 0.1261 - val_accuracy: 0.8225 - val_loss: 0.7575
Epoch 83/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9564 - loss: 0.1181 - val_accuracy: 0.8238 - val_loss: 0.7823
Epoch 84/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9495 - loss: 0.1213 - val_accuracy: 0.8294 - val_loss: 0.8461
Epoch 85/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9502 - loss: 0.1285 - val_accuracy: 0.8175 - val_loss: 0.7088
Epoch 86/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9547 - loss: 0.1190 - val_accuracy: 0.8019 - val_loss: 0.8374
Epoch 87/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9495 - loss: 0.1330 - val_accuracy: 0.8200 - val_loss: 0.8121
Epoch 88/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9578 - loss: 0.1125 - val_accuracy: 0.7969 - val_loss: 0.7743
Epoch 89/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9528 - loss: 0.1276 - val_accuracy: 0.8256 - val_loss: 0.7917
Epoch 90/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9583 - loss: 0.1171 - val_accuracy: 0.8175 - val_loss: 0.8208
Epoch 91/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9603 - loss: 0.1103 - val_accuracy: 0.8231 - val_loss: 0.8252
Epoch 92/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9559 - loss: 0.1140 - val_accuracy: 0.8213 - val_loss: 0.8009
Epoch 93/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9581 - loss: 0.1174 - val_accuracy: 0.8281 - val_loss: 0.8664
Epoch 94/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9592 - loss: 0.1063 - val_accuracy: 0.8100 - val_loss: 0.8086
Epoch 95/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9588 - loss: 0.1150 - val_accuracy: 0.8219 - val_loss: 0.9818
Epoch 96/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9591 - loss: 0.1127 - val_accuracy: 0.8256 - val_loss: 0.8588
Epoch 97/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9603 - loss: 0.1054 - val_accuracy: 0.7994 - val_loss: 0.8385
Epoch 98/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9575 - loss: 0.1131 - val_accuracy: 0.8106 - val_loss: 0.8334
Epoch 99/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9545 - loss: 0.1264 - val_accuracy: 0.8244 - val_loss: 0.8608
Epoch 100/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9569 - loss: 0.1137 - val_accuracy: 0.8206 - val_loss: 0.7853
Epoch 101/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9681 - loss: 0.0870 - val_accuracy: 0.8144 - val_loss: 0.8670
Epoch 102/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9644 - loss: 0.0999 - val_accuracy: 0.8238 - val_loss: 0.8498
Epoch 103/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9559 - loss: 0.1152 - val_accuracy: 0.8037 - val_loss: 0.8637
Epoch 104/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9625 - loss: 0.1072 - val_accuracy: 0.8094 - val_loss: 0.8544
Epoch 105/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9727 - loss: 0.0819 - val_accuracy: 0.8194 - val_loss: 0.8489
Epoch 106/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9634 - loss: 0.1006 - val_accuracy: 0.8306 - val_loss: 0.9939
Epoch 107/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9667 - loss: 0.0965 - val_accuracy: 0.8081 - val_loss: 0.9373
Epoch 108/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9586 - loss: 0.1141 - val_accuracy: 0.8050 - val_loss: 0.8823
Epoch 109/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9616 - loss: 0.1111 - val_accuracy: 0.8238 - val_loss: 0.9896
Epoch 110/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9584 - loss: 0.1101 - val_accuracy: 0.8181 - val_loss: 0.9552
Epoch 111/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9598 - loss: 0.1105 - val_accuracy: 0.8244 - val_loss: 0.8519
Epoch 112/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9656 - loss: 0.0979 - val_accuracy: 0.8231 - val_loss: 0.9261
Epoch 113/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9745 - loss: 0.0797 - val_accuracy: 0.8131 - val_loss: 0.9666
Epoch 114/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9675 - loss: 0.0935 - val_accuracy: 0.7950 - val_loss: 0.9307
Epoch 115/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9747 - loss: 0.0724 - val_accuracy: 0.8031 - val_loss: 0.9030
Epoch 116/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9728 - loss: 0.0798 - val_accuracy: 0.8044 - val_loss: 0.9061
Epoch 117/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9591 - loss: 0.1140 - val_accuracy: 0.8150 - val_loss: 0.9510
Epoch 118/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9638 - loss: 0.1021 - val_accuracy: 0.8075 - val_loss: 0.9618
Epoch 119/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9647 - loss: 0.0969 - val_accuracy: 0.8244 - val_loss: 0.9365
Epoch 120/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9778 - loss: 0.0710 - val_accuracy: 0.8194 - val_loss: 0.9708
Epoch 121/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9736 - loss: 0.0783 - val_accuracy: 0.8138 - val_loss: 0.9440
Epoch 122/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9659 - loss: 0.0958 - val_accuracy: 0.8081 - val_loss: 0.9870
Epoch 123/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9647 - loss: 0.1016 - val_accuracy: 0.8219 - val_loss: 0.9910
Epoch 124/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9680 - loss: 0.0957 - val_accuracy: 0.8050 - val_loss: 0.9998
Epoch 125/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9697 - loss: 0.0932 - val_accuracy: 0.8313 - val_loss: 1.0167
Epoch 126/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 149ms/step - accuracy: 0.9656 - loss: 0.1009 - val_accuracy: 0.8119 - val_loss: 0.9492
Epoch 127/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9794 - loss: 0.0659 - val_accuracy: 0.8175 - val_loss: 0.9459
Epoch 128/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9750 - loss: 0.0757 - val_accuracy: 0.8200 - val_loss: 0.9789
Epoch 129/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9745 - loss: 0.0780 - val_accuracy: 0.8250 - val_loss: 1.2227
Epoch 130/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9684 - loss: 0.1046 - val_accuracy: 0.8169 - val_loss: 0.9607
Epoch 131/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9711 - loss: 0.0842 - val_accuracy: 0.8250 - val_loss: 1.0027
Epoch 132/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9688 - loss: 0.0925 - val_accuracy: 0.8125 - val_loss: 1.0782
Epoch 133/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9711 - loss: 0.0853 - val_accuracy: 0.8269 - val_loss: 0.9523
Epoch 134/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9566 - loss: 0.1214 - val_accuracy: 0.8087 - val_loss: 0.9033
Epoch 135/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9658 - loss: 0.1015 - val_accuracy: 0.8006 - val_loss: 0.9351
Epoch 136/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9741 - loss: 0.0771 - val_accuracy: 0.8281 - val_loss: 0.9997
Epoch 137/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9825 - loss: 0.0592 - val_accuracy: 0.8300 - val_loss: 1.0095
Epoch 138/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9797 - loss: 0.0618 - val_accuracy: 0.8081 - val_loss: 1.1430
Epoch 139/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9753 - loss: 0.0758 - val_accuracy: 0.8056 - val_loss: 1.2358
Epoch 140/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 31s 152ms/step - accuracy: 0.9639 - loss: 0.1029 - val_accuracy: 0.8319 - val_loss: 1.1327
Epoch 141/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 151ms/step - accuracy: 0.9677 - loss: 0.1002 - val_accuracy: 0.8256 - val_loss: 1.0088
Epoch 142/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9780 - loss: 0.0727 - val_accuracy: 0.8244 - val_loss: 0.9750
Epoch 143/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 149ms/step - accuracy: 0.9798 - loss: 0.0632 - val_accuracy: 0.8144 - val_loss: 1.0304
Epoch 144/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9752 - loss: 0.0799 - val_accuracy: 0.8087 - val_loss: 1.0029
Epoch 145/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 150ms/step - accuracy: 0.9733 - loss: 0.0772 - val_accuracy: 0.8250 - val_loss: 1.0980
Epoch 146/400000
200/200 ━━━━━━━━━━━━━━━━━━━━ 30s 152ms/step - accuracy: 0.9756 - loss: 0.0695 - val_accuracy: 0.8394 - val_loss: 1.2520
Epoch 147/400000

KeyboardInterrupt:

In [ ]:
model.layers[0].get_weights()

In [ ]:
y_log = model.predict(X_test_scaled)

In [ ]:
y_pred = np.where(y_log>0.5,1,0)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
history.history()

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

In [ ]:
plt.plot(history.history['accuray'])
plt.plot(history.history['val_accuray'])